# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YFOk9jVfq4r02qRU0eg4R7KE5FBIZll_
"""

# Note: Run 'pip install kagglehub' in terminal if not already installed

"""### 1. Inisialisasi dan Unduh Dataset"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("awsaf49/cbis-ddsm-breast-cancer-image-dataset")

print("Path to dataset files:", path)

"""### 2. Eksplorasi Struktur Direktori Dataset"""

import os
import pandas as pd

# List the contents of the dataset directory
print("Contents of dataset directory:")
for root, dirs, files in os.walk(path):
    level = root.replace(path, '').count(os.sep)
    indent = ' ' * 4 * (level)
    print(f"{indent}{os.path.basename(root)}/")
    subindent = ' ' * 4 * (level + 1)
    # Only show first few files to avoid long output
    for f in files[:5]:
        print(f"{subindent}{f}")
    if len(files) > 5:
        print(f"{subindent}...")

"""### 3. Pemuatan Metadata (CSV)"""

import pandas as pd
import os

# Define paths for the metadata CSVs based on exploration
csv_dir = os.path.join(path, 'csv')

# Load mass and calcification descriptions for train and test sets
calc_train = pd.read_csv(os.path.join(csv_dir, 'calc_case_description_train_set.csv'))
calc_test = pd.read_csv(os.path.join(csv_dir, 'calc_case_description_test_set.csv'))
mass_train = pd.read_csv(os.path.join(csv_dir, 'mass_case_description_train_set.csv'))
mass_test = pd.read_csv(os.path.join(csv_dir, 'mass_case_description_test_set.csv'))

# Concatenate them to get full train and test sets if needed, or inspect one first
print("Columns in Calc Train:", calc_train.columns.tolist())
print("\nSample labels distribution (Pathology):")
print(calc_train['pathology'].value_counts())

calc_train.head()

"""### 4. Pembersihan Data dan Pemetaan Path Gambar"""

import os

def clean_and_prepare(df, base_path):
    # Combine labels: treating BENIGN and BENIGN_WITHOUT_CALLBACK as 0, MALIGNANT as 1
    df['label'] = df['pathology'].apply(lambda x: 1 if 'MALIGNANT' in x else 0)

    # Function to find actual file path since the CSV path might be slightly different from folder structure
    def get_full_path(row):
        # In this dataset, the 'image file path' column typically refers to the parent folder name in 'jpeg/'
        folder_part = row['image file path'].split('/')[0]
        search_dir = os.path.join(base_path, 'jpeg', folder_part)
        if os.path.exists(search_dir):
            for r, d, f in os.walk(search_dir):
                for file in f:
                    if file.endswith('.jpg'):
                        return os.path.join(r, file)
        return None

    df['full_path'] = df.apply(get_full_path, axis=1)
    return df.dropna(subset=['full_path'])

# Combine and clean all datasets
train_df = pd.concat([calc_train, mass_train], ignore_index=True)
test_df = pd.concat([calc_test, mass_test], ignore_index=True)

train_df_cleaned = clean_and_prepare(train_df, path)
test_df_cleaned = clean_and_prepare(test_df, path)

print(f"Training samples after cleaning: {len(train_df_cleaned)}")
print(f"Testing samples after cleaning: {len(test_df_cleaned)}")
print("\nClass Distribution in Train:", train_df_cleaned['label'].value_counts())
print(train_df_cleaned[['full_path', 'label']].head())

import os

# Inspect the CSV paths vs actual directory structure
csv_path_sample = train_df['image file path'].iloc[0]
print(f"Sample path from CSV: {csv_path_sample}")

jpeg_dir = os.path.join(path, 'jpeg')
actual_folders = os.listdir(jpeg_dir)
print(f"First 5 actual folders in 'jpeg/': {actual_folders[:5]}")

# Try to find a match for the first sample
folder_part = csv_path_sample.split('/')[0]
print(f"Looking for folder starting with: {folder_part}")
matches = [f for f in actual_folders if f.startswith(folder_part)]
print(f"Matches found: {matches}")

import os

def find_image_path(csv_path, base_jpeg_dir):
    # The csv_path looks like: Calc-Training_P_00005_RIGHT_CC/UID1/UID2/000000.dcm
    # The actual folder names in 'jpeg' are the UIDs.
    parts = csv_path.split('/')
    if len(parts) < 3:
        return None

    uid_folder = parts[1] # e.g., 1.3.6.1.4.1.9590.100.1.2.408909860712120272633130274602115723157
    search_path = os.path.join(base_jpeg_dir, uid_folder)

    if os.path.exists(search_path):
        for root, dirs, files in os.walk(search_path):
            for file in files:
                if file.endswith('.jpg'):
                    return os.path.join(root, file)
    return None

# Test mapping for the first few rows
print("Testing mapping logic:")
for i in range(5):
    csv_p = train_df['image file path'].iloc[i]
    actual_p = find_image_path(csv_p, jpeg_dir)
    print(f"CSV Path: {csv_p[:50]}... -> Actual: {actual_p}")

# Re-apply cleaning with fixed mapping
def clean_and_prepare_fixed(df, base_jpeg_dir):
    df = df.copy()
    df['label'] = df['pathology'].apply(lambda x: 1 if 'MALIGNANT' in str(x) else 0)
    df['full_path'] = df['image file path'].apply(lambda x: find_image_path(x, base_jpeg_dir))
    return df.dropna(subset=['full_path'])

train_df_cleaned = clean_and_prepare_fixed(train_df, jpeg_dir)
test_df_cleaned = clean_and_prepare_fixed(test_df, jpeg_dir)

print(f"\nFinal Cleaned Train Samples: {len(train_df_cleaned)}")
print(f"Final Cleaned Test Samples: {len(test_df_cleaned)}")
print("Value Counts (Pathology):\n", train_df_cleaned['label'].value_counts())

import os
import pandas as pd

# Load dicom_info.csv which acts as a mapping table
dicom_info = pd.read_csv(os.path.join(csv_dir, 'dicom_info.csv'))

# Create a mapping dictionary: original_path (from metadata) -> processed_jpeg_path
# We normalize paths by replacing .dcm with .jpg or matching folder structures
def get_jpeg_path(row):
    image_path = row['image_path']
    if isinstance(image_path, str):
        # Convert the DICOM path to the local JPEG path format
        # Usually, the jpeg path in dicom_info points to the relative location under 'jpeg/'
        full_jpeg_path = os.path.join(path, 'jpeg', image_path.replace('.dcm', '.jpg'))
        if os.path.exists(full_jpeg_path):
            return full_jpeg_path
    return None

dicom_info['full_path'] = dicom_info.apply(get_jpeg_path, axis=1)
mapping_df = dicom_info.dropna(subset=['full_path'])
path_mapping = dict(zip(mapping_df['image_path'], mapping_df['full_path']))

# Map the paths back to our main dataframes
train_df['full_path'] = train_df['image file path'].map(path_mapping)
test_df['full_path'] = test_df['image file path'].map(path_mapping)

# Prepare labels and drop unmapped rows
train_df_cleaned = train_df.dropna(subset=['full_path']).copy()
test_df_cleaned = test_df.dropna(subset=['full_path']).copy()

train_df_cleaned['label'] = train_df_cleaned['pathology'].apply(lambda x: 1 if 'MALIGNANT' in str(x) else 0)
test_df_cleaned['label'] = test_df_cleaned['pathology'].apply(lambda x: 1 if 'MALIGNANT' in str(x) else 0)

print(f"Mapping Complete.")
print(f"Final Train Samples: {len(train_df_cleaned)}")
print(f"Final Test Samples: {len(test_df_cleaned)}")
if len(train_df_cleaned) > 0:
    print("\nSample Mapping Success:")
    print(train_df_cleaned[['image file path', 'full_path', 'label']].head())
else:
    print("\nMapping still returned 0 results. Checking dicom_info paths...")
    print(dicom_info['image_path'].head())

import os

def fix_path_mapping(df, base_path):
    # Extract the second part of the path (the UID folder) from 'image file path'
    # e.g., 'Calc-Training_P_00005_RIGHT_CC/1.3.6.1.../1.3.6.1.../000000.dcm'
    def get_uid(p):
        if isinstance(p, str):
            parts = p.split('/')
            if len(parts) > 1: return parts[1]
        return None

    df['uid'] = df['image file path'].apply(get_uid)

    # Iterate through jpeg directory to map UID folders to actual file paths
    jpeg_dir = os.path.join(base_path, 'jpeg')
    uid_to_file = {}
    for root, dirs, files in os.walk(jpeg_dir):
        for f in files:
            if f.endswith('.jpg'):
                # The folder name containing the file or its parent is the UID
                parent_folder = os.path.basename(root)
                uid_to_file[parent_folder] = os.path.join(root, f)

    df['full_path'] = df['uid'].map(uid_to_file)
    df['label'] = df['pathology'].apply(lambda x: 1 if 'MALIGNANT' in str(x) else 0)
    return df.dropna(subset=['full_path']).copy()

train_df_cleaned = fix_path_mapping(train_df, path)
test_df_cleaned = fix_path_mapping(test_df, path)

print(f"Success! Train samples: {len(train_df_cleaned)}")
print(f"Success! Test samples: {len(test_df_cleaned)}")
if len(train_df_cleaned) > 0:
    print("\nExample paths:")
    print(train_df_cleaned[['full_path', 'label']].head())
    print("\nClass Distribution:")
    print(train_df_cleaned['label'].value_counts())

import os

# Sample from CSV metadata
print("Sample CSV image file path components:")
sample_csv_path = train_df['image file path'].iloc[0]
print(f"Original: {sample_csv_path}")
print(f"Split parts: {sample_csv_path.split('/')}")

# Explore actual directory structure deeper
print("\nExploring actual directory structure in 'jpeg/':")
count = 0
for root, dirs, files in os.walk(os.path.join(path, 'jpeg')):
    if files:
        rel_path = os.path.relpath(root, os.path.join(path, 'jpeg'))
        print(f"Relative path: {rel_path} | Files: {files[:2]}")
        count += 1
    if count >= 5:
        break

# Try matching based on common UID strings found in both
csv_uids = set()
for p in train_df['image file path'].head(10):
    csv_uids.update(p.split('/'))

print(f"\nUID parts from first 10 CSV rows: {list(csv_uids)[:5]}")

import os
import pandas as pd

def map_images_to_metadata(df, base_path):
    # Extract all possible UIDs from the 'image file path' column
    # The format is 'Project_Patient_Laterality_View/UID1/UID2/000000.dcm'
    def get_potential_uids(p):
        if isinstance(p, str):
            return set(p.split('/'))
        return set()

    # Map every UID folder in the jpeg directory to its actual .jpg file path
    jpeg_dir = os.path.join(base_path, 'jpeg')
    uid_map = {}
    for root, dirs, files in os.walk(jpeg_dir):
        for f in files:
            if f.endswith('.jpg'):
                # Use the immediate parent folder name as the key (UID)
                uid_map[os.path.basename(root)] = os.path.join(root, f)

    def match_path(p):
        uids = get_potential_uids(p)
        for uid in uids:
            if uid in uid_map:
                return uid_map[uid]
        return None

    df = df.copy()
    df['full_path'] = df['image file path'].apply(match_path)
    df['label'] = df['pathology'].apply(lambda x: 1 if 'MALIGNANT' in str(x) else 0)

    cleaned_df = df.dropna(subset=['full_path']).copy()
    return cleaned_df

# Re-process train and test data
train_df_cleaned = map_images_to_metadata(train_df, path)
test_df_cleaned = map_images_to_metadata(test_df, path)

print(f"Finalized Train samples: {len(train_df_cleaned)}")
print(f"Finalized Test samples: {len(test_df_cleaned)}")

if len(train_df_cleaned) > 0:
    print("\nSample distribution:")
    print(train_df_cleaned['label'].value_counts())
    print("\nFirst few mapped entries:")
    print(train_df_cleaned[['full_path', 'label']].head())
else:
    print("\nMapping still failed. Listing first 10 keys in uid_map for debugging:")
    # Recalculate map locally to show debug info
    debug_map = {}
    for root, dirs, files in os.walk(os.path.join(path, 'jpeg')):
        if files: debug_map[os.path.basename(root)] = files[0]
        if len(debug_map) > 10: break
    print(list(debug_map.keys()))

"""### 5. Preprocessing Gambar dan Pembuatan Dataset TensorFlow (ROI & CLAHE)"""

import tensorflow as tf
import cv2
import numpy as np
import pandas as pd
import os

# 1. Re-load the metadata CSVs to restore kernel state
csv_dir = os.path.join(path, 'csv')
calc_train = pd.read_csv(os.path.join(csv_dir, 'calc_case_description_train_set.csv'))
calc_test = pd.read_csv(os.path.join(csv_dir, 'calc_case_description_test_set.csv'))
mass_train = pd.read_csv(os.path.join(csv_dir, 'mass_case_description_train_set.csv'))
mass_test = pd.read_csv(os.path.join(csv_dir, 'mass_case_description_test_set.csv'))

# 2. Re-establish cleaned dataframes
train_df = pd.concat([calc_train, mass_train], ignore_index=True)
train_df_cleaned = map_images_to_metadata(train_df, path)
test_df = pd.concat([calc_test, mass_test], ignore_index=True)
test_df_cleaned = map_images_to_metadata(test_df, path)

IMG_SIZE = (224, 224)
BATCH_SIZE = 32

def preprocess_pipeline(image):
    # Nested function to ensure it's in scope for tf.py_function
    def remove_artifacts_and_extract_roi_local(image_arg):
        # 1. Thresholding to create a mask of the breast
        gray = cv2.cvtColor(np.uint8(image_arg * 255), cv2.COLOR_RGB2GRAY)
        _, thresh = cv2.threshold(gray, 10, 255, cv2.THRESH_BINARY)

        # 2. Find the largest contour (the breast)
        contours, _ = cv2.findContours(thresh, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
        if not contours:
            return image_arg

        largest_cnt = max(contours, key=cv2.contourArea)
        mask = np.zeros_like(gray)
        cv2.drawContours(mask, [largest_cnt], -1, 255, -1)

        # 3. Apply mask
        result = cv2.bitwise_and(np.uint8(image_arg * 255), np.uint8(image_arg * 255), mask=mask)

        # 4. Crop to bounding box
        x, y, w, h = cv2.boundingRect(largest_cnt)
        roi = result[y:y+h, x:x+w]

        # Resize back to target size
        roi_resized = cv2.resize(roi, (224, 224))
        return np.float32(roi_resized) / 255.0

    image_roi = remove_artifacts_and_extract_roi_local(image)
    img_uint8 = np.uint8(image_roi * 255)
    denoised = cv2.medianBlur(img_uint8, 3)
    clahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8,8))
    channels = cv2.split(denoised)
    clahe_channels = [clahe.apply(c) for c in channels]
    result = cv2.merge(clahe_channels)
    return np.float32(result) / 255.0

def load_and_preprocess_image(path, label):
    img = tf.io.read_file(path)
    img = tf.image.decode_jpeg(img, channels=3)
    img = tf.image.resize(img, IMG_SIZE)
    img = img / 255.0
    [img,] = tf.py_function(preprocess_pipeline, [img], [tf.float32])
    img.set_shape((*IMG_SIZE, 3))
    return img, label

def create_dataset(df, shuffle=True):
    paths = df['full_path'].values
    labels = df['label'].values
    ds = tf.data.Dataset.from_tensor_slices((paths, labels))
    ds = ds.map(load_and_preprocess_image, num_parallel_calls=tf.data.AUTOTUNE)
    if shuffle: ds = ds.shuffle(buffer_size=1000)
    ds = ds.batch(BATCH_SIZE).prefetch(buffer_size=tf.data.AUTOTUNE)
    return ds

if len(train_df_cleaned) > 0:
    train_ds = create_dataset(train_df_cleaned, shuffle=True)
    test_ds = create_dataset(test_df_cleaned, shuffle=False)
    print(f"Pipeline sukses. Sampel latih: {len(train_df_cleaned)}")
else:
    print("Error: train_df_cleaned masih kosong. Cek logika pemetaan.")

"""### 6. Augmentasi Data dan Visualisasi"""

import matplotlib.pyplot as plt
from tensorflow.keras import layers, Sequential

# 1. Define data augmentation layers
data_augmentation = Sequential([
    layers.RandomFlip("horizontal_and_vertical"),
    layers.RandomRotation(0.2),
    layers.RandomZoom(0.1),
])

# 2 & 3. Update the training dataset to include augmentation
# We apply augmentation as a mapping step on the already batched dataset for efficiency
augmented_train_ds = train_ds.map(
    lambda x, y: (data_augmentation(x, training=True), y),
    num_parallel_calls=tf.data.AUTOTUNE
)

# 4. Visualize a few augmented samples
plt.figure(figsize=(10, 10))
for images, labels in augmented_train_ds.take(1):
    for i in range(9):
        ax = plt.subplot(3, 3, i + 1)
        plt.imshow(images[i].numpy())
        plt.title(f"Label: {labels[i].numpy()}")
        plt.axis("off")
plt.suptitle("Augmented Training Samples")
plt.show()

"""### 7. Membangun dan Melatih Model CNN DenseNet121"""

from tensorflow.keras.applications import DenseNet121
from tensorflow.keras.models import Model
from tensorflow.keras import layers, optimizers

# Using DenseNet121 for better feature propagation in medical imaging
base_model = DenseNet121(input_shape=(224, 224, 3), include_top=False, weights='imagenet')
base_model.trainable = False

x = base_model.output
x = layers.GlobalAveragePooling2D()(x)
x = layers.BatchNormalization()(x)
x = layers.Dense(256, activation='relu')(x)
x = layers.Dropout(0.4)(x) # Increased dropout for regularization
predictions = layers.Dense(1, activation='sigmoid')(x)

model = Model(inputs=base_model.input, outputs=predictions)

# Learning rate scheduler can be added here for optimization
model.compile(
    optimizer=optimizers.Adam(learning_rate=1e-4),
    loss='binary_crossentropy',
    metrics=['accuracy', tf.keras.metrics.AUC(name='auc'), tf.keras.metrics.Recall(name='recall'), tf.keras.metrics.Precision(name='precision')]
)

print("Model updated to DenseNet121 with clinical metrics.")
epochs = 15
history = model.fit(augmented_train_ds, validation_data=test_ds, epochs=epochs)

"""### 8. Visualisasi Riwayat Pelatihan (Accuracy & AUC)"""

def plot_history(history):
    acc = history.history['accuracy']
    val_acc = history.history['val_accuracy']
    auc = history.history['auc']
    val_auc = history.history['val_auc']
    loss = history.history['loss']
    val_loss = history.history['val_loss']
    epochs_range = range(len(acc))

    plt.figure(figsize=(15, 5))
    plt.subplot(1, 2, 1)
    plt.plot(epochs_range, acc, label='Training Accuracy')
    plt.plot(epochs_range, val_acc, label='Validation Accuracy')
    plt.title('Training and Validation Accuracy')
    plt.legend()

    plt.subplot(1, 2, 2)
    plt.plot(epochs_range, auc, label='Training AUC')
    plt.plot(epochs_range, val_auc, label='Validation AUC')
    plt.title('Training and Validation AUC')
    plt.legend()
    plt.show()

plot_history(history)

"""### 9. Evaluasi Model: Confusion Matrix dan Classification Report"""

import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix, classification_report

print("Memulai prediksi pada dataset test...")

# Melakukan prediksi
y_pred_prob = model.predict(test_ds)
y_pred = (y_pred_prob > 0.5).astype(int).flatten()

# Mengambil label asli
y_true = np.concatenate([y for x, y in test_ds], axis=0)

# Kalkulasi metrics
cm = confusion_matrix(y_true, y_pred)
tn, fp, fn, tp = cm.ravel()

sensitivity = tp / (tp + fn) if (tp + fn) > 0 else 0
specificity = tn / (tn + fp) if (tn + fp) > 0 else 0

print(f"Sensitivity (Recall): {sensitivity:.4f}")
print(f"Specificity: {specificity:.4f}")
print("\nClassification Report:\n", classification_report(y_true, y_pred, target_names=['Benign', 'Malignant']))

# Visualisasi Confusion Matrix
plt.figure(figsize=(6, 5))
sns.heatmap(cm, annot=True, fmt='d', cmap='Reds', xticklabels=['Benign', 'Malignant'], yticklabels=['Benign', 'Malignant'])
plt.title('Confusion Matrix - Hasil Prediksi')
plt.ylabel('True Label')
plt.xlabel('Predicted Label')
plt.show()

"""### 10. Implementasi Arsitektur Attention U-Net"""

from tensorflow.keras import layers, models, backend as K
import tensorflow as tf

def attention_block(x, gating, inter_shape):
    shape_x = K.int_shape(x)
    phi_g = layers.Conv2D(inter_shape, (1, 1), padding='same')(gating)
    theta_x = layers.Conv2D(inter_shape, (1, 1), strides=(1, 1), padding='same')(x)
    concat_xg = layers.add([theta_x, phi_g])
    act_xg = layers.Activation('relu')(concat_xg)
    psi_xg = layers.Conv2D(1, (1, 1), padding='same')(act_xg)
    sigmoid_xg = layers.Activation('sigmoid')(psi_xg)
    y = layers.multiply([sigmoid_xg, x])
    result = layers.Conv2D(shape_x[3], (1, 1), padding='same')(y)
    result_bn = layers.BatchNormalization()(result)
    return result_bn

def conv_block(x, filters):
    x = layers.Conv2D(filters, (3, 3), padding="same")(x)
    x = layers.BatchNormalization()(x)
    x = layers.Activation("relu")(x)
    x = layers.Conv2D(filters, (3, 3), padding="same")(x)
    x = layers.BatchNormalization()(x)
    x = layers.Activation("relu")(x)
    return x

def build_attention_unet_classifier(input_shape=(224, 224, 3)):
    inputs = layers.Input(input_shape)

    # Encoder
    c1 = conv_block(inputs, 64)
    p1 = layers.MaxPooling2D((2, 2))(c1)
    c2 = conv_block(p1, 128)
    p2 = layers.MaxPooling2D((2, 2))(c2)
    c3 = conv_block(p2, 256)
    p3 = layers.MaxPooling2D((2, 2))(c3)
    c4 = conv_block(p3, 512)
    p4 = layers.MaxPooling2D((2, 2))(c4)

    # Bridge
    b1 = conv_block(p4, 1024)

    # Decoder
    u1 = layers.Conv2DTranspose(512, (2, 2), strides=(2, 2), padding='same')(b1)
    att1 = attention_block(x=c4, gating=u1, inter_shape=512)
    c5 = conv_block(layers.concatenate([u1, att1]), 512)

    u2 = layers.Conv2DTranspose(256, (2, 2), strides=(2, 2), padding='same')(c5)
    att2 = attention_block(x=c3, gating=u2, inter_shape=256)
    c6 = conv_block(layers.concatenate([u2, att2]), 256)

    u3 = layers.Conv2DTranspose(128, (2, 2), strides=(2, 2), padding='same')(c6)
    att3 = attention_block(x=c2, gating=u3, inter_shape=128)
    c7 = conv_block(layers.concatenate([u3, att3]), 128)

    u4 = layers.Conv2DTranspose(64, (2, 2), strides=(2, 2), padding='same')(c7)
    att4 = attention_block(x=c1, gating=u4, inter_shape=64)
    c8 = conv_block(layers.concatenate([u4, att4]), 64)

    # Classifier Head (Added to match scalar labels)
    # We keep a named conv layer for Grad-CAM access
    last_conv = layers.Conv2D(64, (3, 3), padding='same', activation='relu', name='last_conv_layer')(c8)
    gap = layers.GlobalAveragePooling2D()(last_conv)
    output = layers.Dense(1, activation='sigmoid', name='final_output')(gap)

    model = models.Model(inputs=[inputs], outputs=[output], name="Attention_UNet_Classifier")
    return model

model_attn = build_attention_unet_classifier()
print("Attention U-Net Classifier successfully updated to handle scalar labels.")

import cv2
import numpy as np

def remove_artifacts_and_extract_roi(image):
    # 1. Thresholding to create a mask of the breast
    gray = cv2.cvtColor(np.uint8(image * 255), cv2.COLOR_RGB2GRAY)
    _, thresh = cv2.threshold(gray, 10, 255, cv2.THRESH_BINARY)

    # 2. Find the largest contour (the breast)
    contours, _ = cv2.findContours(thresh, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    if not contours:
        return image

    largest_cnt = max(contours, key=cv2.contourArea)
    mask = np.zeros_like(gray)
    cv2.drawContours(mask, [largest_cnt], -1, 255, -1)

    # 3. Apply mask
    result = cv2.bitwise_and(np.uint8(image * 255), np.uint8(image * 255), mask=mask)

    # 4. Crop to bounding box
    x, y, w, h = cv2.boundingRect(largest_cnt)
    roi = result[y:y+h, x:x+w]

    # Resize back to target size
    roi_resized = cv2.resize(roi, (224, 224))
    return np.float32(roi_resized) / 255.0

print("Advanced Preprocessing (ROI & Artifact Removal) functions defined.")

import tensorflow as tf
from tensorflow.keras import backend as K

def dice_loss(y_true, y_pred):
    y_true = tf.cast(y_true, tf.float32)
    numerator = 2 * tf.reduce_sum(y_true * y_pred)
    denominator = tf.reduce_sum(y_true + y_pred)
    return 1 - (numerator + 1e-6) / (denominator + 1e-6)

# Re-compile Attention U-Net with Dice Loss
model_attn.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-4),
    loss=dice_loss,
    metrics=['accuracy', tf.keras.metrics.AUC(name='auc')]
)

print("Attention U-Net re-compiled with Dice Loss for medical segmentation optimization.")

from sklearn.metrics import precision_recall_curve

def tune_threshold(model, dataset):
    y_true = []
    y_scores = []

    for imgs, labels in dataset:
        preds = model.predict(imgs, verbose=0)
        y_true.extend(labels.numpy())
        y_scores.extend(preds.flatten())

    precisions, recalls, thresholds = precision_recall_curve(y_true, y_scores)
    f1_scores = 2 * (precisions * recalls) / (precisions + recalls + 1e-10)
    best_idx = np.argmax(f1_scores)
    best_threshold = thresholds[best_idx]

    print(f"Optimal Threshold found: {best_threshold:.4f}")
    print(f"Best F1-Score: {f1_scores[best_idx]:.4f}")
    return best_threshold

# threshold_opt = tune_threshold(model_attn, test_ds)

"""### 11. Interpretabilitas Model dengan Grad-CAM"""

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.cm as cm
import tensorflow as tf

def get_gradcam(img_array, model, last_conv_layer_name=None):
    # Jika nama layer tidak diberikan, cari layer konvolusi terakhir secara otomatis
    if last_conv_layer_name is None:
        for layer in reversed(model.layers):
            if isinstance(layer, tf.keras.layers.Conv2D):
                last_conv_layer_name = layer.name
                break

    print(f"Menggunakan layer untuk Grad-CAM: {last_conv_layer_name}")

    grad_model = tf.keras.models.Model(
        inputs=[model.inputs],
        outputs=[model.get_layer(last_conv_layer_name).output, model.output]
    )

    with tf.GradientTape() as tape:
        conv_outputs, predictions = grad_model(img_array)
        loss = tf.reduce_mean(predictions)

    grads = tape.gradient(loss, conv_outputs)
    pooled_grads = tf.reduce_mean(grads, axis=(0, 1, 2))

    conv_outputs = conv_outputs[0]
    heatmap = conv_outputs @ pooled_grads[..., tf.newaxis]
    heatmap = tf.squeeze(heatmap)

    heatmap = tf.maximum(heatmap, 0) / (tf.reduce_max(heatmap) + 1e-10)
    return heatmap.numpy()

# Ambil contoh gambar dari test_ds
for images, labels in test_ds.take(1):
    sample_img = images[0:1]
    sample_label = labels[0]

# Memanggil Grad-CAM (biarkan mencari layer otomatis)
heatmap = get_gradcam(sample_img, model_attn)

# Visualisasi
img_np = sample_img[0].numpy()
plt.figure(figsize=(12, 6))
plt.subplot(1, 2, 1)
plt.imshow(img_np)
plt.title(f"Original Image (Label: {'Malignant' if sample_label==1 else 'Benign'})")
plt.axis('off')

plt.subplot(1, 2, 2)
plt.imshow(img_np)
# Resize heatmap agar sesuai ukuran gambar input (224, 224)
resized_heatmap = tf.image.resize(heatmap[..., np.newaxis], (224, 224)).numpy()
plt.imshow(resized_heatmap, alpha=0.5, cmap='jet')
plt.title("Attention U-Net Grad-CAM")
plt.axis('off')
plt.show()

"""### 13. Visualisasi Mendalam: Feature Maps, Attention Maps, dan Grad-CAM"""

import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

def get_gradcam(img_array, model, last_conv_layer_name=None):
    if last_conv_layer_name is None:
        for layer in reversed(model.layers):
            if isinstance(layer, tf.keras.layers.Conv2D):
                last_conv_layer_name = layer.name
                break

    grad_model = tf.keras.models.Model(
        inputs=[model.inputs],
        outputs=[model.get_layer(last_conv_layer_name).output, model.output]
    )

    with tf.GradientTape() as tape:
        conv_outputs, predictions = grad_model(img_array)
        loss = tf.reduce_mean(predictions)

    grads = tape.gradient(loss, conv_outputs)
    pooled_grads = tf.reduce_mean(grads, axis=(0, 1, 2))

    conv_outputs = conv_outputs[0]
    heatmap = conv_outputs @ pooled_grads[..., tf.newaxis]
    heatmap = tf.squeeze(heatmap)
    heatmap = tf.maximum(heatmap, 0) / (tf.reduce_max(heatmap) + 1e-10)
    return heatmap.numpy()

def visualize_attention_unet_internals(model, dataset):
    for images, labels in dataset.take(1):
        img = images[0:1]
        label = labels[0]
        break

    layer_outputs = []
    layer_names = []

    for layer in model.layers:
        if len(layer.output.shape) == 4:
            if 'conv2d_7' in layer.name or 'last_conv_layer' in layer.name:
                layer_outputs.append(layer.output)
                layer_names.append(layer.name)
            if 'activation' in layer.name and 'sigmoid' in layer.name and 'final' not in layer.name:
                layer_outputs.append(layer.output)
                layer_names.append("Attention Gate")

    if not layer_outputs:
        print("Tidak ditemukan layer yang cocok untuk visualisasi.")
        return

    vis_model = tf.keras.models.Model(inputs=model.input, outputs=layer_outputs)
    activations = vis_model.predict(img)
    if not isinstance(activations, list):
        activations = [activations]

    plt.figure(figsize=(24, 6))

    plt.subplot(1, 4, 1)
    plt.imshow(img[0].numpy())
    plt.title(f"Original Image\nLabel: {'Malignant' if label==1 else 'Benign'}")
    plt.axis('off')

    plt.subplot(1, 4, 2)
    feat_map = activations[0][0]
    if len(feat_map.shape) == 3:
        feat_map = np.mean(feat_map, axis=-1)
    plt.imshow(feat_map, cmap='viridis')
    plt.title(f"Feature Map: {layer_names[0]}")
    plt.axis('off')

    plt.subplot(1, 4, 3)
    attn_map = activations[-1][0]
    if len(attn_map.shape) == 3:
        attn_map = np.mean(attn_map, axis=-1)
    plt.imshow(attn_map, cmap='hot')
    plt.title("Attention Gate Map")
    plt.axis('off')

    plt.subplot(1, 4, 4)
    heatmap = get_gradcam(img, model)
    resized_heatmap = tf.image.resize(heatmap[..., np.newaxis], (224, 224)).numpy()
    plt.imshow(img[0].numpy())
    plt.imshow(resized_heatmap, alpha=0.5, cmap='jet')
    plt.title("Grad-CAM Focus")
    plt.axis('off')

    plt.tight_layout()
    plt.show()

visualize_attention_unet_internals(model_attn, test_ds)

"""### 14. Membangun dan Melatih Model CNN ResNet50

ResNet (Residual Networks) adalah arsitektur CNN lain yang sangat efektif, terutama untuk jaringan yang sangat dalam. Kunci dari ResNet adalah penggunaan 'residual connections' atau 'skip connections' yang memungkinkan informasi melewati beberapa lapisan. Ini membantu mengatasi masalah vanishing gradient dan memungkinkan pelatihan model yang lebih dalam dan lebih akurat. Kami akan menggunakan ResNet50 yang sudah dilatih sebelumnya dari `imagenet` sebagai feature extractor.
"""

from tensorflow.keras.applications import ResNet50
from tensorflow.keras.models import Model
from tensorflow.keras import layers, optimizers

# Memuat ResNet50 sebagai model dasar
# input_shape harus sesuai dengan ukuran gambar Anda, include_top=False untuk tidak menyertakan lapisan klasifikasi ImageNet
# weights='imagenet' untuk menggunakan bobot yang sudah dilatih sebelumnya
base_model_resnet = ResNet50(input_shape=(224, 224, 3), include_top=False, weights='imagenet')

# Bekukan lapisan base_model agar tidak dilatih ulang
base_model_resnet.trainable = False

# Tambahkan lapisan klasifikasi kustom di atas output ResNet50
x = base_model_resnet.output
x = layers.GlobalAveragePooling2D()(x) # Mengurangi dimensi spasial menjadi vektor fitur
x = layers.BatchNormalization()(x)
x = layers.Dense(256, activation='relu')(x) # Lapisan Dense dengan 256 unit dan aktivasi ReLU
x = layers.Dropout(0.4)(x) # Dropout untuk regularisasi
predictions = layers.Dense(1, activation='sigmoid')(x) # Lapisan output untuk klasifikasi biner dengan aktivasi Sigmoid

# Buat model lengkap
model_resnet = Model(inputs=base_model_resnet.input, outputs=predictions, name="ResNet50_Classifier")

# Kompilasi model
model_resnet.compile(
    optimizer=optimizers.Adam(learning_rate=1e-4),
    loss='binary_crossentropy',
    metrics=['accuracy', tf.keras.metrics.AUC(name='auc'), tf.keras.metrics.Recall(name='recall'), tf.keras.metrics.Precision(name='precision')]
)

print("Model ResNet50 berhasil dibuat dan dikompilasi.")

# Latih model
epochs_resnet = 15 # Sesuaikan jumlah epoch jika diperlukan
history_resnet = model_resnet.fit(augmented_train_ds, validation_data=test_ds, epochs=epochs_resnet)

"""### 15. Visualisasi Riwayat Pelatihan ResNet50 (Accuracy & AUC)

Mari kita visualisasikan performa pelatihan dan validasi dari model ResNet50.
"""

import matplotlib.pyplot as plt

def plot_history_resnet(history):
    acc = history.history['accuracy']
    val_acc = history.history['val_accuracy']
    auc = history.history['auc']
    val_auc = history.history['val_auc']
    loss = history.history['loss']
    val_loss = history.history['val_loss']
    epochs_range = range(len(acc))

    plt.figure(figsize=(15, 5))
    plt.subplot(1, 2, 1)
    plt.plot(epochs_range, acc, label='Training Accuracy')
    plt.plot(epochs_range, val_acc, label='Validation Accuracy')
    plt.title('Training and Validation Accuracy (ResNet50)')
    plt.legend()

    plt.subplot(1, 2, 2)
    plt.plot(epochs_range, auc, label='Training AUC')
    plt.plot(epochs_range, val_auc, label='Validation AUC')
    plt.title('Training and Validation AUC (ResNet50)')
    plt.legend()
    plt.show()

plot_history_resnet(history_resnet)

"""### 16. Evaluasi Model ResNet50: Confusion Matrix dan Classification Report

Sekarang kita akan mengevaluasi performa model ResNet50 pada data uji menggunakan Confusion Matrix dan Classification Report.
"""

import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix, classification_report

print("Memulai prediksi pada dataset test untuk ResNet50...")

# Melakukan prediksi
y_pred_prob_resnet = model_resnet.predict(test_ds)
y_pred_resnet = (y_pred_prob_resnet > 0.5).astype(int).flatten()

# Mengambil label asli (sudah tersedia dari DenseNet)
# y_true = np.concatenate([y for x, y in test_ds], axis=0)

# Kalkulasi metrics
cm_resnet = confusion_matrix(y_true, y_pred_resnet)
tn, fp, fn, tp = cm_resnet.ravel()

sensitivity_resnet = tp / (tp + fn) if (tp + fn) > 0 else 0
specificity_resnet = tn / (tn + fp) if (tn + fp) > 0 else 0

print(f"Sensitivity (Recall) ResNet50: {sensitivity_resnet:.4f}")
print(f"Specificity ResNet50: {specificity_resnet:.4f}")
print("\nClassification Report ResNet50:\n", classification_report(y_true, y_pred_resnet, target_names=['Benign', 'Malignant']))

# Visualisasi Confusion Matrix
plt.figure(figsize=(6, 5))
sns.heatmap(cm_resnet, annot=True, fmt='d', cmap='Blues', xticklabels=['Benign', 'Malignant'], yticklabels=['Benign', 'Malignant'])
plt.title('Confusion Matrix - ResNet50')
plt.ylabel('True Label')
plt.xlabel('Predicted Label')
plt.show()

"""### 17. Membangun dan Melatih Model CNN EfficientNetB0

EfficientNet adalah keluarga model yang dikembangkan oleh Google yang menggunakan penskalaan majemuk (compound scaling) untuk mencapai akurasi yang lebih baik dengan efisiensi yang lebih tinggi. Kami akan menggunakan EfficientNetB0, varian terkecil, sebagai model dasar untuk transfer learning.
"""

from tensorflow.keras.applications import EfficientNetB0
from tensorflow.keras.models import Model
from tensorflow.keras import layers, optimizers

# Memuat EfficientNetB0 sebagai model dasar
base_model_efficientnet = EfficientNetB0(input_shape=(224, 224, 3), include_top=False, weights='imagenet')

# Bekukan lapisan base_model
base_model_efficientnet.trainable = False

# Tambahkan lapisan klasifikasi kustom
x = base_model_efficientnet.output
x = layers.GlobalAveragePooling2D()(x)
x = layers.BatchNormalization()(x)
x = layers.Dense(256, activation='relu')(x)
x = layers.Dropout(0.4)(x)
predictions = layers.Dense(1, activation='sigmoid')(x)

# Buat model lengkap
model_efficientnet = Model(inputs=base_model_efficientnet.input, outputs=predictions, name="EfficientNetB0_Classifier")

# Kompilasi model
model_efficientnet.compile(
    optimizer=optimizers.Adam(learning_rate=1e-4),
    loss='binary_crossentropy',
    metrics=['accuracy', tf.keras.metrics.AUC(name='auc'), tf.keras.metrics.Recall(name='recall'), tf.keras.metrics.Precision(name='precision')]
)

print("Model EfficientNetB0 berhasil dibuat dan dikompilasi.")

# Latih model
epochs_efficientnet = 15 # Sesuaikan jumlah epoch jika diperlukan
history_efficientnet = model_efficientnet.fit(augmented_train_ds, validation_data=test_ds, epochs=epochs_efficientnet)

"""### 18. Visualisasi Riwayat Pelatihan EfficientNetB0 (Accuracy & AUC)

Mari kita visualisasikan performa pelatihan dan validasi dari model EfficientNetB0.
"""

import matplotlib.pyplot as plt

def plot_history_efficientnet(history):
    acc = history.history['accuracy']
    val_acc = history.history['val_accuracy']
    auc = history.history['auc']
    val_auc = history.history['val_auc']
    loss = history.history['loss']
    val_loss = history.history['val_loss']
    epochs_range = range(len(acc))

    plt.figure(figsize=(15, 5))
    plt.subplot(1, 2, 1)
    plt.plot(epochs_range, acc, label='Training Accuracy')
    plt.plot(epochs_range, val_acc, label='Validation Accuracy')
    plt.title('Training and Validation Accuracy (EfficientNetB0)')
    plt.legend()

    plt.subplot(1, 2, 2)
    plt.plot(epochs_range, auc, label='Training AUC')
    plt.plot(epochs_range, val_auc, label='Validation AUC')
    plt.title('Training and Validation AUC (EfficientNetB0)')
    plt.legend()
    plt.show()

plot_history_efficientnet(history_efficientnet)

"""### 19. Evaluasi Model EfficientNetB0: Confusion Matrix dan Classification Report

Sekarang kita akan mengevaluasi performa model EfficientNetB0 pada data uji menggunakan Confusion Matrix dan Classification Report.
"""

import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix, classification_report

print("Memulai prediksi pada dataset test untuk EfficientNetB0...")

# Melakukan prediksi
y_pred_prob_efficientnet = model_efficientnet.predict(test_ds)
y_pred_efficientnet = (y_pred_prob_efficientnet > 0.5).astype(int).flatten()

# Menggunakan label asli yang sudah ada dari evaluasi DenseNet
# y_true = np.concatenate([y for x, y in test_ds], axis=0)

# Kalkulasi metrics
cm_efficientnet = confusion_matrix(y_true, y_pred_efficientnet)
tn, fp, fn, tp = cm_efficientnet.ravel()

sensitivity_efficientnet = tp / (tp + fn) if (tp + fn) > 0 else 0
specificity_efficientnet = tn / (tn + fp) if (tn + fp) > 0 else 0

print(f"Sensitivity (Recall) EfficientNetB0: {sensitivity_efficientnet:.4f}")
print(f"Specificity EfficientNetB0: {specificity_efficientnet:.4f}")
print("\nClassification Report EfficientNetB0:\n", classification_report(y_true, y_pred_efficientnet, target_names=['Benign', 'Malignant']))

# Visualisasi Confusion Matrix
plt.figure(figsize=(6, 5))
sns.heatmap(cm_efficientnet, annot=True, fmt='d', cmap='Greens', xticklabels=['Benign', 'Malignant'], yticklabels=['Benign', 'Malignant'])
plt.title('Confusion Matrix - EfficientNetB0')
plt.ylabel('True Label')
plt.xlabel('Predicted Label')
plt.show()

